# Generated by Django 4.1.7 on 2023-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('surface_coords', models.CharField(blank=True, max_length=15, null=True)),
                ('kop', models.FloatField(blank=True, null=True)),
                ('targets', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
